before:
  hooks:
  - go mod tidy

builds:
  - main: .
    ldflags:
     - -s -w
     - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
